name: 'terraform-plan-approve-apply' # 'Hello World'
description: 'Greet someone'
inputs:
  working-directory:
    description: 'Working directory for this action'
    required: false
    default: '.'
  who-to-greet:  # ID of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}. ${{ inputs.working-directory }}
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      working-directory: ${{ inputs.working-directory }}
