on: [push]
  push:
    paths:
      - test-workspace-triggers/sub-1

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install and Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - id: foo
        uses: ./.github/actions/terraform-workflow # actions/hello-world-composite-run-steps-action@v1
        with:
          working-directory: 'test-workspace-triggers/sub-1'
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
